### ISSUE TITLE
[2.0.1] Fatal Exception on com.patloew.rxfit.SingleResultCallBack.get

### ISSUE THREAD

**Issue by skawue** [patloew/RxFit#6]
Hello everybody!

I have some problem with this library (v2.0.1). I cannot reproduce this error on my devices but it happens on many of my clients' devices.

Fabric shows me this:
```
#0. Crashed: main: 0 0 0x0000000000000000
       at io.reactivex.plugins.RxJavaPlugins.isFailOnNonBlockingScheduler(Unknown Source)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(Unknown Source)
       at com.patloew.rxfit.SingleResultCallBack.get(Unknown Source)
       at com.google.android.gms.internal.zzbcs.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

--

Fatal Exception: io.b.c.f: com.patloew.rxfit.t: Status{statusCode=The connection to Google Play services was lost, resolution=null}
       at io.reactivex.plugins.RxJavaPlugins.isFailOnNonBlockingScheduler(Unknown Source)
       at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(Unknown Source)
       at com.patloew.rxfit.SingleResultCallBack.get(Unknown Source)
       at com.google.android.gms.internal.zzbcs.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by com.patloew.rxfit.t: Status{statusCode=The connection to Google Play services was lost, resolution=null}
       at com.patloew.rxfit.SingleResultCallBack.get(Unknown Source)
       at com.google.android.gms.internal.zzbcs.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Now I am reading about RxJavaPlugins.setErrorHandler(). Is it a problem?

Thank you for any help!

**Comment by justin-000** [comment]
I'm seeing the same crash as well for several users.
